<<<<<<< HEAD
# Scenario Name
scenario: 'baseline'
=======
# Scenario Name 
scenario: "India"
>>>>>>> fa0d330e55b11ad7ed12cef6e3511867be11db31

# Change input data - run script after inputs are generated
custom_data: True

# Temporal Parameters
startYear: 2025
endYear: 2050
daytype: False
dayparts:
  #daypart : [start_hour (inclusive), end_hour (exclusive)]
  D1: [1, 7]
  D2: [7, 13]
  D3: [13, 19]
  D4: [19, 25]
seasons:
  #season : [month 1, month 2, ...] (all inclusive)
  S1: [1, 2, 3, 4, 5, 6]
  S2: [7, 8, 9, 10, 11, 12]

timeshift: 0 # value between -11 and 12
  
# Spatial Parameters 
geographic_scope:
  - 'USA'

crossborderTrade: False

# Emission Parameters 
emission_penalty: 
# - [EMISSION, COUNTRY, START_YEAR, END_YEAR, VALUE]
# where VALUE is in M$/MT CO2
 - ['CO2', 'USA', 2020, 2050, 0]

# Investment Parameters 
no_invest_technologies: 
  - "CSP"
  - "WAV"
  - "URN"
  - "OTH"
  - "WAS"
  - "COG" 
  - "GEO"
  - "BIO"
  - "PET"

# Result Parameters
results_by_country: False

# solver parameters
solver: 'gurobi' # cbc, cplex, gurobi

user_defined_capacity:
  # technology: [capacity, 
  #              first_year, 
  #              "fixed/open", 
  #              first_year_of_expansion, 
  #              build_rate_per_year, 
  #              cost]
  TRNINDEAINDNE: [0, 2030, "open", 2030, 10, 861]

nodes_to_add:
 #- 'AAAXX' where AAA is a 3-letter country code,
 # specified in the 'geographic scope'
 # and XX is a 2-letter sub-regional node code.
 # E.g. - 'IDNSM' for a sub-regional node in Sumatra, Indonesia.
 # - 'IDNSM'


nodes_to_remove:
#- "AAAXX" where AAA is a 3-letter country code, and XX is a 2-letter 
# sub-national code

powerplant_build_rates:
 # [TECHNOLOGY, COUNTRY, METHOD, VALUE, START_YEAR, END_YEAR]
 # where TECHNOLOGY_TYPE is, for example, all coal powerplants and is in the 
 # format COA.
 # COUNTRY is the 3-letter country code. E.g. "IND" for "Indonesia" 
 # METHOD specifies how the build rate is applied: absolute ("ABS" or as a 
 # percentage ("PCT") of the maximum capacity for a TECHNOLOGY_TYPE.
 # VALUE is the value - either absolute or percentage - by which the capacity 
 # of the associated TECHNOLOGY can increase. It is applied from the START_YEAR 
 # to the END_YEAR.
 # E.g. - ["SPV", "IND", "ABS", 0, 2020, 2025] 
  - ["SPV", "IND", "PCT", 25, 2020, 2025] 

reserve_margin:
# RESERVE_MARGIN: [PERCENTAGE, START_YEAR, END_YEAR]
# Years for which there is no PERCENTAGE value will be interpolated
  RM1: [15, 2030, 2050]

emission_limit:
# - [EMISSION, COUNTRY, YEAR, VALUE]
# where VALUE is emissions in million tonnes of CO2-equivalent and YEAR is  
# when that constraint must be adhered to. All years between multiple emission 
# constraints will be interpolated.
# - ['CO2', 'IDN', 2040, 1]

fuel_limits:
# FUEL: [VALUE, COUNTRY/INTERNATIONAL, YEAR]
# Where FUEL is the fuel on which a limit is being applied (e.g. COA), VALUE is
# the value in Petajoules (PJ), COUNTRY/INTERNATIONAL specific which domestic 
# fuel (e.g. IND) or international fuel ("INT") the limit is being applied to, 
# and YEAR is the year for which the limit is applied. All years between multiple 
# fuel extraction constraints will be interpolated.


calibration:
#  OCG1: [50, "IND", 2021]

re_targets:
# E.g. - ["IND", 2030, 2040, 30]
# where "IND" is the country code; 2030, 2040 are the start and end years
# respectively; and 30 is the target between the start and end years (inclusive)
# in %
 - ["USA", 2030, 2040, 30]
